<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_authors"
 *
 * Auto generated by Extension Builder 2014-08-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'RKW Authors',
	'description' => 'Extension for handling authorship of pages',
	'category' => 'plugin',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel.de',
    'author_company' => 'RKW Kompetenzzentrum',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '7.6.13',
	'constraints' => array(
		'depends' => array(
            'extbase' => '6.2.0-7.6.99',
            'fluid' => '6.2.0-7.6.99',
            'typo3' => '6.2.0-7.6.99',
            'rkw_basics' => '7.6.12-7.6.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);