<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_authors"
 *
 * Auto generated by Extension Builder 2014-08-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Authors',
	'description' => 'Extension for handling authorship of pages',
	'category' => 'plugin',
	'author' => 'Maximilian Fäßler, Steffen Kroggel',
	'author_email' => 'maximilian@faesslerweb.de, developer@steffenkroggel.de',
    'author_company' => 'RKW Kompetenzzentrum',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '8.7.5',
	'constraints' => [
		'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'rkw_basics' => '8.7.0-8.7.99'
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];